version: '3'

services:
  webapp:
    image: webapp
    restart: always
    build:
      context: ./frontend-client
    container_name: webapp-c
    ports:
      - "8080:8080"

  api:
    image: api
    restart: always
    working_dir: /storefront
    build:
      context: ./storefront
    container_name: api-c
    volumes:
      - ./storefront/storefront:/storefront
      - ~/.m2:/root/.m2
    ports:
      - "8081:8081"

  bk-food:
    image: bk-food
    restart: always
    build:
      context: ./food-service
    working_dir: /food-service
    container_name: food-c
    ports:
      - "8084:8084"
    depends_on: 
      - mongo

  bk-user:
    image: bk-user
    restart: always
    working_dir: /userService
    build:
      context: ./userService
    container_name: user-c
    volumes:
      - ./userService:/userservice
    ports:
      - "8083:8083"
    depends_on: 
      - mongo

  bk-order:
    image: bk-order
    restart: always
    working_dir: /orderProcessingService
    build:
      context: ./orderProcessingService
    volumes:
      - ./orderProcessingService:/orderProcessingService
    ports:
      - "8082:8082"
    depends_on: 
      - mongo
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis-service:
    image: redis
    ports:
      - "6379:6379"
