package project.mpp.foodservice.rest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import project.mpp.foodservice.domain.Food;
import project.mpp.foodservice.persistence.FoodRepository;
import project.mpp.foodservice.service.FoodService;

@RestController // This means that this class is a Controller
public class GetAllFood {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private FoodRepository foodRepository;

    @Autowired
    private FoodService service;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Food> getAllFood() {
        // This returns a JSON or XML with the users
        return foodRepository.findAll();
    }

    @GetMapping(path="/restaurant/{restaurantId}")
    public @ResponseBody Iterable<Food> getAllFood(@PathVariable String restaurantId) {
        // This returns a JSON or XML with the users
        return foodRepository.findAllFoodByRestaurantId(restaurantId);
    }
}
